Cobra refactor
twopt/ClickupCLI pull request #2
Opened 2021-10-21 04:03 UTC by fantasticrabbit

2021-10-21 22:00 UTC, Andrew-Kulpa commented on cmd/root.go
> +	// has an action associated with it:
Is this comment still needed?

2021-10-21 22:00 UTC, Andrew-Kulpa commented on cmd/version.go
> +	// versionCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
Is this comment still needed?

2021-10-21 22:01 UTC, Andrew-Kulpa commented on cmd/root.go
> +	// will be global for your application.
Are these comments still needed?

2021-11-02 18:18 UTC, fantasticrabbit commented
• Resolved bug with ~/.clickup/config.yaml file not creating properly.  
• moved get task to a proper sub command, passing taskID as an argument, (and added optional filtering for the # character that the Clickup web app tends to add when using it's copy-button function)

2021-11-04 12:49 UTC, Andrew-Kulpa requested changes

2021-11-04 12:49 UTC, Andrew-Kulpa commented on Makefile
> +PKG := github.com/fantasticrabbit/$(NAME)cli
Isn't the package under `twopt`?

2021-11-04 12:49 UTC, Andrew-Kulpa commented on README.md
> +1. The first time the app is used, it will open a browser and ask the user to log in to ClickUp to give the client app permission to exchange data with the corresponding workspace. The client may onl
It would be interesting to see how this might work on a terminal-only environment. For instance, with GAM the flow may be something like:
> Depending on your choices, either a website will open automatically or you'll be given a URL to go to to authorize GAM to create projects as the admin you specified. Click allow, copy the code if given one and switch back to the GAM window.

2021-11-04 12:49 UTC, Andrew-Kulpa commented on cmd/task.go
> +}
Are we planning on exposing the query parameters? For example:
- custom_task_ids
- team_id
- include_subtasks

2021-11-04 12:49 UTC, Andrew-Kulpa commented on README.md
> +1. From the Clickup app, copy the TaskID for the task you'd like to retrieve (e.g. `#123456`).
If we're not supporting custom task IDs yet, that should be noted here.

2021-11-04 12:49 UTC, Andrew-Kulpa commented on cmd/task.go
> +		}
Its just one line, but you could deduplicate the GetTask calls here by pulling `data := internal.GetTask(taskID, token, clientID)` out of this conditional.

2021-11-04 12:49 UTC, Andrew-Kulpa commented on internal/gettask.go
>  		fmt.Println("Errored when sending request to the server")
Should this message and the corresponding error be returned? Also, wouldn't you want this going to STDERR?

2021-11-04 12:49 UTC, Andrew-Kulpa commented on internal/auth.go
> +				log.Println("Failed to shutdown server", err)
Should this be going to STDERR?

Example: https://stackoverflow.com/a/40694000

2021-11-04 12:49 UTC, Andrew-Kulpa commented on internal/auth.go
> +	log.Println(server.ListenAndServe())
Should this also be going to STDERR?

2021-11-04 12:49 UTC, Andrew-Kulpa commented on cmd/root.go
> +	"github.com/fantasticrabbit/ClickupCLI/internal"
Should this be `github.com/twopt/...`?

2021-11-04 12:49 UTC, Andrew-Kulpa commented on cmd/task.go
> +		}
It might be better to handle this with `PreRunE` like shown here: https://stackoverflow.com/a/63856623

2021-11-04 12:49 UTC, Andrew-Kulpa commented on cmd/task.go
> +		taskID := strings.Replace(strings.Join(args, ","), "#", "", -1)
You already validate that there should only be 1 argument. There's no need to join a single-element array.

You could probably use `strings.Trim()` and it would be more clear.

For example: `taskId := strings.Trim(args[0], "#")`

2021-11-04 12:54 UTC, Andrew-Kulpa commented on internal/auth.go
> +	log.Println(server.ListenAndServe())
I'll also add [this interesting perspective](https://news.ycombinator.com/item?id=12688462) on STDOUT vs STDERR for these kinds of messages:
> I would constrain this even further to "Write to stdout only if information is useful as input to another program."

> Even useful information for a human reader can make downstream integration overbearingly complex if the information is intermingled with a lot of extraneous, albeit human-readable, information. Machine-readable layouts (structured somehow: csv, tsv, json, xml, etc.) are vastly more useful for integration.

2021-11-08 20:53 UTC, fantasticrabbit commented on cmd/task.go
> +}
I think custom task IDs is a contender for next-needed feature, and you need team ID for that.  But team ID seems to be available as a prefix in the auth key itself, so not sure about requiring user to supply it, but this probably needs a little further validation.  But include_subtasks seems to me to need a lot more thought, along the lines of general "get tasks" implementation questions, like, all 1 JSON, and at that point should we be trying to prettify that output?

I'd really like to get the Go testing setup, and the refactoring that will require done first. Then have the main task fetch working before adding any new functionality, including custom task IDs, so I can make sure nothing is getting broken as this goes forward.

2021-11-08 21:15 UTC, fantasticrabbit commented on cmd/task.go
> +		taskID := strings.Replace(strings.Join(args, ","), "#", "", -1)
good callout, had this stuff working in a separate test application and copied over to this, need to add "spend a day running through the strings package" to my list. :)

Done.

2021-11-08 22:22 UTC, Andrew-Kulpa commented on cmd/task.go
> +}
The Team ID could be optional 🤷‍♂️ 

I'm cool with getting the base task fetching done first and having this as a follow-up.

2021-11-09 00:44 UTC, fantasticrabbit commented on cmd/task.go
> +		}
Did some research, and I think the Args: field inside the command struct for Cobra is the place to put this check.
https://pkg.go.dev/github.com/spf13/cobra@v1.2.1#Command

2021-11-09 00:45 UTC, fantasticrabbit commented on cmd/task.go
> +		}
cleaned up some of the other vars set in this block including this.

2021-11-09 00:48 UTC, fantasticrabbit commented on internal/auth.go
> +	log.Println(server.ListenAndServe())
Log writes to stderr by default: https://pkg.go.dev/log

Did a site-wide cleanup of logging and exiting using log.fatalln to provide precise exit codes along with the log message to stderr.

2021-11-09 19:17 UTC, fantasticrabbit commented on cmd/task.go
> +}
Per the API notes on Team ID: 
"Only used when the parameter is set to custom_task_ids=true"

That leads me to believe it's required for the custom task request (which makes a little sense, you might have overlap between two orgs).

2021-11-10 04:52 UTC, merged

2021-11-11 19:01 UTC, fantasticrabbit commented on cmd/get.go
> +	Use:   "get",
Done, moved this convo to PR #6

2021-11-11 19:03 UTC, fantasticrabbit commented on Makefile
> +PKG := github.com/fantasticrabbit/$(NAME)cli
keeping under fantasticrabbit for now.

2021-11-11 19:04 UTC, fantasticrabbit commented on README.md
> +1. The first time the app is used, it will open a browser and ask the user to log in to ClickUp to give the client app permission to exchange data with the corresponding workspace. The client may onl
interesting future feature

2021-11-11 19:06 UTC, fantasticrabbit commented on cmd/task.go
> +}
During refactor for test setup, these became very easy and are done, just need a path for setting the Team ID in the configuration.

2021-11-11 19:06 UTC, fantasticrabbit commented on internal/auth.go
> +				log.Println("Failed to shutdown server", err)
Yes, and log.Println sends them there.

2021-11-11 19:06 UTC, fantasticrabbit commented on README.md
> +1. From the Clickup app, copy the TaskID for the task you'd like to retrieve (e.g. `#123456`).
supported now.

2021-11-11 19:07 UTC, fantasticrabbit commented on cmd/root.go
> +	"github.com/fantasticrabbit/ClickupCLI/internal"
keeping as is for now.

2021-11-11 19:08 UTC, fantasticrabbit commented on internal/gettask.go
>  		fmt.Println("Errored when sending request to the server")
Yes, fixed, also this was moved into requester.go.