Cobra refactor with tests
twopt/ClickupCLI pull request #6
Opened 2021-11-11 18:59 UTC by fantasticrabbit

Replacing the initial cobra refactor PR that was accidentally merged.

Refactor to implement cobra/viper and abstracted http requests for setting up tests.

2021-11-11 19:00 UTC, fantasticrabbit commented
https://github.com/twopt/ClickupCLI/pull/2#discussion_r735843045

Per Artur's comments, pulled task out to subcommand on "get"

2021-11-11 19:15 UTC, fantasticrabbit commented
https://github.com/twopt/ClickupCLI/pull/2#discussion_r735970790

I think auth flow is probably the only open discussion item from PR #2, need a path for setting up Team ID, and will think on this as I flesh out more tests and then will formalize this draft request.

2021-11-12 21:18 UTC, fantasticrabbit commented
OK, removed the fileout logic, you're both right about it.
Implemented a "set" command, to set the Redirect Port, or Team ID, needed for task requests using custom IDs.
Moved some of the auth logic around to trigger only when needed.
I'm ready for your feedback, please be brutal. :)

2021-11-16 23:14 UTC, Andrew-Kulpa reviewed
This is looking great! I had a few comments, but honestly I love the way this is going.

2021-11-16 23:14 UTC, Andrew-Kulpa commented on cmd/root.go
> +			log.Fatalln("auth failed")
Is it worth including the `err` in this fatal log line?

2021-11-16 23:14 UTC, Andrew-Kulpa commented on cmd/set.go
> +	setCmd.Flags().StringP("token", "", "", "set the Auth Token manually")
It looks like you have to keep these in sync with the string array on line 23. To deduplicate this and make it more scalable, what if we used a package variable for `setFlags` like the following:
```golang
setFlags := map[string]string{
    "team": "set the Team ID",
    "port":   "set the Redirect URL Port number",
    "token": "set the Auth Token manually",
}
```

Then you could get the keys directly using `keys := reflect.ValueOf(setFlags).MapKeys()` and iterate over them in this `init()` function like this: `for flag, description := range setFlags {...}`.

2021-11-16 23:14 UTC, Andrew-Kulpa commented on internal/getlist.go
> +type ListRequest struct {
I like that these are all predefined. Goes a bit against `YAGNI` but it seems inconsequential.

2021-11-16 23:14 UTC, Andrew-Kulpa commented on internal/requester.go
> +}
Does it make sense for this to be in the `requester.go` file when it has nothing to do with the actual requesting?

2021-11-16 23:37 UTC, fantasticrabbit commented on internal/requester.go
> +}
do you think a new internal/format.go file makes sense here, instead?

2021-11-16 23:39 UTC, fantasticrabbit commented on internal/getlist.go
> +type ListRequest struct {
yeah, came out while testing and seemed at least a nice way to document in the code.

2021-11-16 23:40 UTC, fantasticrabbit commented on cmd/set.go
> +	setCmd.Flags().StringP("token", "", "", "set the Auth Token manually")
that's a great idea, I've been studying the reflect package as a way to tackle that giant list of task list parameters, will try that here first.

2021-11-17 05:13 UTC, fantasticrabbit commented on internal/getlist.go
> +type ListRequest struct {
I will drop this here, because I'm thinking about if this is really the best way to do this. 

Basically the 2 options I'm weighing are, either follow the API documentation, which is around "target nouns" (tasks, lists, being the big ones), or follow the API paths which is around where does the info come from.

The Clickup documentation puts the get task and get tasks stuff together.  But, "get tasks" uses \api\v2\list\... and the singular task hits \api\v2\task\.... So, I started putting the "get tasks [all tasks in a list by list ID] under here (getlist.go), thinking it would end up something like:
   1. `clickup get list LISTID` command, which fetches info about the list, and then 
   2. `clickup get list LISTID --tasks` (or maybe a subcommand?) which fetches a set of tasks, with list-orders\filters\etc...

But then, using that logic, the list requests become:
   1. `clickup get list LISTID`
   2. `clickup get folder FOLDERID --lists`
   3. `clickup get space SPACE_ID --lists`

Which seems "not ideal", using 3 different commands for getting very similar info types.

So, re-thinking this. Maybe I should follow the documentation and use the "verb object-noun" organization and push the "list of tasks" request back under `clickup get task list LISTID`, (giving me `clickup get list LISTID`, `clickup get list folder FOLDERID`, `clickup get list space SPACE_ID`.

Thoughts, suggested reading, other alternatives?

2021-11-17 18:14 UTC, Andrew-Kulpa commented on internal/getlist.go
> +type ListRequest struct {
What if we just match the current API? For example:
```bash
clickup get list LISTID
clickup get lists FOLDERID [--[no]-archived]
clickup get folderless-lists SPACEID [--[no]-archived]
```

They all can use the same list interface for the set of returned lists, stay under the `get` subcommand, but be handled differently for their respective API routes.

2021-11-17 18:14 UTC, Andrew-Kulpa commented on internal/requester.go
> +}
I think that makes sense.

2021-11-17 19:04 UTC, fantasticrabbit commented on internal/getlist.go
> +type ListRequest struct {
Well...because I have a blind preference to keep the commands as simple as possible and making list/lists/folderless-lists, task/tasks/3-other-too-long-names, etc. seemed like too much user knowledge.

Mostly I just **really** want all the various "item"/"items" to use the same command. 

But yeah, I'm often irrational and this third way seems right to me. (And a little obvious, now that I look back at myself cringing every time I looked at their documentation for Task getting internally pissed off about there being a get task, get tasks, get list, get lists, etc.). I get it, I get it.

2021-11-18 20:39 UTC, fantasticrabbit commented on cmd/root.go
> +			log.Fatalln("auth failed")
Looks like errors are handled upstream, but included here in case.

2021-11-18 20:41 UTC, fantasticrabbit commented on cmd/set.go
> +	setCmd.Flags().StringP("token", "", "", "set the Auth Token manually")
applied package var map, using range to iterate over the key/values in the map, not sure why I would need the reflect here.  implemented, let me know if you had something better in mind by using the reflection package.

2021-11-18 20:42 UTC, fantasticrabbit commented on internal/getlist.go
> +type ListRequest struct {
list is done, working through the tasks breakout next.

2021-11-18 20:42 UTC, fantasticrabbit commented on internal/requester.go
> +}
done.

2021-11-19 15:39 UTC, Andrew-Kulpa approved these changes
LGTM

2021-12-14 04:52 UTC, artur-sak13 requested changes
There are a few areas that can be improved (mostly Go "gotchas") but overall I really like where this is going. This is really impressive work especially considering that it's one of the first things you've ever written in Go. Excellent job!

By the way, are you planning on keeping the libraries under your "fantasticrabbit" namespace or do you plan on moving it under @twopt's?

2021-12-14 04:52 UTC, artur-sak13 commented on cmd/getlists.go
> +			return errors.New("incorrect number of arguments")
I suggest making this error message more informative to the user by specifying the minimum number of arguments this command is expecting.

2021-12-14 04:52 UTC, artur-sak13 commented on cmd/getlists.go
> +	Use:   "lists FOLDERID [-a]",
You don't need to include the `[-a]` here because the usage message already lists the flags. See below:

```text
Request JSON data for all lists by folder ID

Usage:
  clickup get lists FOLDERID [-a] [flags]

Flags:
  -a, --archived   include archived lists in output
  -h, --help       help for lists

Global Flags:
      --config string   config file (default: /home/someuser/.clickup/config.yaml)
```

2021-12-14 04:52 UTC, artur-sak13 commented on cmd/get.go
> +	Run:   func(cmd *cobra.Command, args []string) {},
You can remove the `Run` command here since it's currently a no-op.

2021-12-14 04:52 UTC, artur-sak13 commented on cmd/getlist.go
> +		internal.Request(l)
`Request()` shouldn't be directly attached to the `internal` package; it should be encapsulated in a concrete package (with a more descriptive name).

2021-12-14 04:52 UTC, artur-sak13 commented on cmd/getlists_folderless.go
> +	Use:   "folderless-lists SPACEID [-a]",
Same as above, you don't need the `[-a]` because the usage message already includes it.

2021-12-14 04:52 UTC, artur-sak13 commented on cmd/set.go
> +package cmd
Honestly, I don't think you need to include a `set` command at this point. The config file won't be modified frequently (and probably shouldn't) and you can always override with inline environment variables (e.g. `$ CLICKUP_TEAM_ID=example CLICKUP_TOKEN=pk_xxxxx clickup get task 9hz`).

2021-12-21 15:45 UTC, fantasticrabbit commented on .goosarch
> +windows/arm64
sure, ruin the symmetry. done.

2021-12-21 16:05 UTC, fantasticrabbit commented on cmd/root.go
> +	Version: "v0.1.7",
Done.

2021-12-21 16:08 UTC, fantasticrabbit commented on README.md
> +export CLICKUP_PORT=9999
Removed from the readme for now, configuration might be handy in case it ever conflicted with an existing service.

2021-12-21 16:11 UTC, fantasticrabbit commented on cmd/root.go
>  	Run: func(cmd *cobra.Command, args []string) {
Done.

2021-12-21 16:11 UTC, fantasticrabbit commented on cmd/root.go
> +// initConfig reads in config file, ENV variables if set, and determines authentication steps
Done.

2021-12-21 16:36 UTC, fantasticrabbit commented on cmd/root.go
> +	config_file = (home + "/.clickup/config.yaml")
switched to filepath.join, keeping these 2 global now, I think it makes sense for this use case.

2021-12-21 17:45 UTC, fantasticrabbit commented on cmd/getlists_folderless.go
> +	Use:   "folderless-lists SPACEID [-a]",
Done.

2021-12-21 17:45 UTC, fantasticrabbit commented on cmd/get.go
> +	Run:   func(cmd *cobra.Command, args []string) {},
Done.

2021-12-21 17:51 UTC, fantasticrabbit commented on cmd/set.go
> +package cmd
I feel like it's a better way of generally providing Team ID. In certain use cases Team ID may not always be the same (think members of different teams using separate Clickup Spaces, but accessing from the same environment) so a machine environment variable may not work.

2021-12-21 18:00 UTC, fantasticrabbit commented on cmd/root.go
> +		_, err := os.Stat(config_path)
I'll take a deeper look at this, I was not getting expected results using the viper WriteConfig functions, and this was how I got it working.

2021-12-21 18:14 UTC, fantasticrabbit commented on cmd/root.go
> +			errDir := os.MkdirAll(config_path, 0755)
log doesn't implement %w, but the rest of this makes sense.  As always, thanks for the reading links.

2021-12-21 18:19 UTC, fantasticrabbit commented on cmd/getlists.go
> +			return errors.New("incorrect number of arguments")
Done.

2021-12-21 18:33 UTC, fantasticrabbit commented on internal/auth.go
> +	testAPIbaseV2 = "https://localhost/api/v2"
Done.

2021-12-21 18:33 UTC, fantasticrabbit commented on internal/auth.go
> +	testAPIbase   = "https://localhost/api"
Nope, removed.

2021-12-21 19:44 UTC, artur-sak13 commented on cmd/set.go
> +package cmd
I'm not suggesting a machine environment variable but a user-provided one. I have to do this all the time when using the `aws-cli` (or any related tooling), to get information from/deploy to our various AWS accounts. Each team member should have their own config and credentials even if they are on the same environment. One person swapping/overriding their Team ID shouldn't affect anyone else.

2021-12-21 19:46 UTC, artur-sak13 commented on cmd/root.go
> +			errDir := os.MkdirAll(config_path, 0755)
Ah, I always get that confused with [`sirupsen/logrus`](https://github.com/sirupsen/logrus); the `log` package uses `%v` instead.

2021-12-21 22:08 UTC, artur-sak13 commented on cmd/root.go
> +	config_file = (home + "/.clickup/config.yaml")
Can you explain how/why it makes sense for this use case?

2021-12-22 05:43 UTC, fantasticrabbit commented on cmd/root.go
> +	config_file = (home + "/.clickup/config.yaml")
Because the config file is needed on every command, shouldn't the var holding it's path always be available?. Except, after re-reading this blog post, I think I understand better and agree with Mr. Bourgon and am afraid of the amount of re-factoring. :)

2022-01-12 23:46 UTC, fantasticrabbit commented on cmd/root.go
> +		viper.WriteConfigAs(config_file)
Done.

2022-01-12 23:46 UTC, fantasticrabbit commented on internal/requester.go
> +package internal
Done.

2022-01-12 23:46 UTC, fantasticrabbit commented on internal/requester.go
> +}
Done.

2022-01-12 23:46 UTC, fantasticrabbit commented on internal/requester.go
> +)
Done.

2022-01-12 23:47 UTC, fantasticrabbit commented on cmd/getlist.go
> +		internal.Request(l)
Done.

2022-01-12 23:47 UTC, fantasticrabbit commented on cmd/root.go
> +	config_file = (home + "/.clickup/config.yaml")
Done.

2022-01-15 00:58 UTC, artur-sak13 requested changes

2022-01-15 00:58 UTC, artur-sak13 commented on api/requester.go
> +package api
`api` is misleading. When I see a package named `api` I usually expect it to contain _server-side_ code exposing a limited interface that other pieces of software can use to interact with the backend. I'd probably put this under a package called `client`. Here's a [good reference layout](https://github.com/golang-standards/project-layout) showing how to structure Go repos.

2022-01-15 00:58 UTC, artur-sak13 commented on cmd/getlists.go
> +	},
You can replace this with `cobra.ExactArgs(1)`

2022-01-15 00:58 UTC, artur-sak13 commented on cmd/getlists_folderless.go
> +	},
You can replace this with `cobra.ExactArgs(1)`

2022-01-15 00:58 UTC, artur-sak13 commented on cmd/gettask.go
> +	},
You can replace this with `cobra.ExactArgs(1)`

2022-01-15 00:58 UTC, artur-sak13 commented on cmd/getlist.go
> +	},
You can replace this with `cobra.ExactArgs(1)`

2022-01-15 00:58 UTC, artur-sak13 commented on cmd/set.go
> +				println("Saved", flag, "in config file")
Replace this with `fmt.Printf("Saved %s to %s\n", flag, utils.GetConfigFile())` to keep it consistent (i.e. log through the `log` and `fmt` packages).

2022-01-15 00:58 UTC, artur-sak13 commented on cmd/set.go
> +	"port":  "set the Redirect URL Port number",
For some reason, it won't let me respond to the [other conversation](https://github.com/twopt/ClickupCLI/pull/6#discussion_r773263770) so I'll move it over here.

>I wouldn't leave the port configurable in this case. If this was a service then that would make more sense, but given the target users and the fact that the port is only used for the callback URL (i.e. it's ephemeral), it's an unnecessary detail that the user shouldn't have to worry about.
>>Removed from the readme for now, configuration might be handy in case it ever conflicted with an existing service.

That shouldn't be an issue because it's using an [ephemeral port](https://en.wikipedia.org/wiki/Ephemeral_port) and should only be open for as long as it's serving the redirect page. Don't keep code around because it "might" be handy, YAGNI. If you're really concerned with port collisions if you listen on port 0, the OS should allocate an available port for you.

2022-01-20 20:45 UTC, fantasticrabbit commented on cmd/set.go
> +	"port":  "set the Redirect URL Port number",
Did not know these extended port ranges were considered ephemeral, good info.  Removing the port item from set.

2022-01-20 20:46 UTC, fantasticrabbit commented on cmd/set.go
> +				println("Saved", flag, "in config file")
done.

2022-01-20 20:46 UTC, fantasticrabbit commented on cmd/getlist.go
> +	},
done.

2022-01-20 20:46 UTC, fantasticrabbit commented on cmd/gettask.go
> +	},
done

2022-01-20 20:46 UTC, fantasticrabbit commented on cmd/getlists_folderless.go
> +	},
done.

2022-01-20 20:46 UTC, fantasticrabbit commented on cmd/getlists.go
> +	},
done.

2022-01-20 20:48 UTC, fantasticrabbit commented on api/requester.go
> +package api
nice, I copied the api from Github's cli package, but, I agree that client is more appropriate.

2022-01-20 20:48 UTC, fantasticrabbit commented on internal/auth.go
> +	if !viper.InConfig("token") || viper.GetString("token") == "" {
done.

2022-01-20 20:50 UTC, fantasticrabbit commented on internal/auth.go
> +func CheckToken() bool {
I changed to CheckTokenExists.

2022-01-20 20:52 UTC, fantasticrabbit commented on cmd/set.go
> +	},
Didn't even know these checks were available! Kicking myself that I put entirely too much thought into these input validators just to find out this has already been solved. Done.

2022-01-20 21:02 UTC, artur-sak13 approved these changes
Excellent! LGTM!

2022-01-20 22:17 UTC, merged